// Code generated by Kitex v0.7.0. DO NOT EDIT.

package socialservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	SocialService "github.com/cold-runner/simpleTikTok/kitex_gen/SocialService"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentAction(ctx context.Context, Req *SocialService.CommentActionRequest, callOptions ...callopt.Option) (r *SocialService.CommentActionResponse, err error)
	CommentList(ctx context.Context, Req *SocialService.CommentListRequest, callOptions ...callopt.Option) (r *SocialService.CommentListResponse, err error)
	LikeAction(ctx context.Context, Req *SocialService.LikeActionRequest, callOptions ...callopt.Option) (r *SocialService.LikeActionResponse, err error)
	LikeList(ctx context.Context, Req *SocialService.LikeListRequest, callOptions ...callopt.Option) (r *SocialService.LikeListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) CommentAction(ctx context.Context, Req *SocialService.CommentActionRequest, callOptions ...callopt.Option) (r *SocialService.CommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, Req)
}

func (p *kSocialServiceClient) CommentList(ctx context.Context, Req *SocialService.CommentListRequest, callOptions ...callopt.Option) (r *SocialService.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, Req)
}

func (p *kSocialServiceClient) LikeAction(ctx context.Context, Req *SocialService.LikeActionRequest, callOptions ...callopt.Option) (r *SocialService.LikeActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeAction(ctx, Req)
}

func (p *kSocialServiceClient) LikeList(ctx context.Context, Req *SocialService.LikeListRequest, callOptions ...callopt.Option) (r *SocialService.LikeListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeList(ctx, Req)
}
