// Code generated by Kitex v0.7.0. DO NOT EDIT.
package socialservice

import (
	server "github.com/cloudwego/kitex/server"
	SocialService "github.com/cold-runner/simpleTikTok/kitex_gen/SocialService"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler SocialService.SocialService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
