// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChat = "chat"

// Chat mapped from table <chat>
type Chat struct {
	ID        int64     `gorm:"column:id;type:int;primaryKey" json:"id,string"`
	UserID    int64     `gorm:"column:user_id;type:int" json:"user_id"`
	Content   string    `gorm:"column:content;type:text" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	Object    int64     `gorm:"column:object;type:int" json:"object"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
