// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChat = "chat"

// Chat mapped from table <chat>
type Chat struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	UserID    int32     `gorm:"column:user_id" json:"user_id"`
	Content   string    `gorm:"column:content" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	Object    int32     `gorm:"column:object" json:"object"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
