// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "message"

// Comment mapped from table <message>
type Comment struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	UserID    int32     `gorm:"column:user_id" json:"user_id"`
	Content   string    `gorm:"column:content" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	VedioID   int32     `gorm:"column:vedio_id" json:"vedio_id"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
