// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFriend = "friend"

// Friend mapped from table <friend>
type Friend struct {
	ID       int32 `gorm:"column:id;primaryKey" json:"id"`
	UserID   int32 `gorm:"column:user_id" json:"user_id"`
	FriendID int32 `gorm:"column:friend_id" json:"friend_id"`
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
