// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoLike = "video_like"

// VideoLike mapped from table <video_like>
type VideoLike struct {
	ID      int64 `gorm:"column:id;type:int;primaryKey" json:"id,string"`
	UserID  int64 `gorm:"column:user_id;type:int" json:"user_id"`
	VideoID int64 `gorm:"column:video_id;type:int" json:"video_id"`
}

// TableName VideoLike's table name
func (*VideoLike) TableName() string {
	return TableNameVideoLike
}
