// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Chat:      newChat(db, opts...),
		Comment:   newComment(db, opts...),
		Follow:    newFollow(db, opts...),
		Friend:    newFriend(db, opts...),
		User:      newUser(db, opts...),
		Video:     newVideo(db, opts...),
		VideoLike: newVideoLike(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Chat      chat
	Comment   comment
	Follow    follow
	Friend    friend
	User      user
	Video     video
	VideoLike videoLike
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Chat:      q.Chat.clone(db),
		Comment:   q.Comment.clone(db),
		Follow:    q.Follow.clone(db),
		Friend:    q.Friend.clone(db),
		User:      q.User.clone(db),
		Video:     q.Video.clone(db),
		VideoLike: q.VideoLike.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Chat:      q.Chat.replaceDB(db),
		Comment:   q.Comment.replaceDB(db),
		Follow:    q.Follow.replaceDB(db),
		Friend:    q.Friend.replaceDB(db),
		User:      q.User.replaceDB(db),
		Video:     q.Video.replaceDB(db),
		VideoLike: q.VideoLike.replaceDB(db),
	}
}

type queryCtx struct {
	Chat      *chatDo
	Comment   *commentDo
	Follow    *followDo
	Friend    *friendDo
	User      *userDo
	Video     *videoDo
	VideoLike *videoLikeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Chat:      q.Chat.WithContext(ctx),
		Comment:   q.Comment.WithContext(ctx),
		Follow:    q.Follow.WithContext(ctx),
		Friend:    q.Friend.WithContext(ctx),
		User:      q.User.WithContext(ctx),
		Video:     q.Video.WithContext(ctx),
		VideoLike: q.VideoLike.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
